Azure/deco

app/controllers/welcome.js, app/index.html, app/styles/app.scss, app/templates/welcome.hbs, config/nw-config.js, package.json
- Better Window positions & sizes
- Cursor for ember data actions
=> Improve NW.js Style

app/models/blob.js, app/routes/explorer.js, app/styles/app.scss, app/styles/explorer.scss, app/styles/navbar.scss, app/templates/_navbar.hbs, app/templates/explorer.hbs
- Simple template with styles
- Extended blob model
=> Initial Explorer View

app/adapters/blob.js, app/adapters/container.js, app/controllers/welcome.js, app/models/blob.js, app/models/container.js, app/routes/explorer.js, app/templates/explorer.hbs, tests/unit/models/container-test.js
Demonstrated rendering container names and container blob counts (sort of). Tests are baked into welcome controller and are commented out. We need a way to run nw tests from the harness.
=> Added more adapter implementation and some view integration

app/components/ax-spinner.js, app/controllers/welcome.js, app/styles/welcome.scss, app/templates/components/ax-spinner.hbs, app/templates/welcome.hbs, tests/unit/components/ax-spinner-test.js
- New loading spinner component (`ax-spinner`)
- Spinner used on welcome route
=> Loading Spinner

app/controllers/explorer.js, app/templates/explorer.hbs, package.json
Closes #19
- Lists blobs for the containers
=> Show blobs

app/controllers/explorer.js, app/styles/app.scss, app/styles/explorer.scss, app/templates/explorer.hbs
Closes #20 
- No progress yet, but it does initiate a download of the blob
=> Add Download Feature

README.md, tests/integration/welcome-test.js, tests/unit/routes/welcome-test.js
A first round of integration tests, specifically for the `/welcome`
route.
=> Welcome: Integration Tests

app/adapters/container.js, app/controllers/explorer.js, app/routes/explorer.js, app/styles/explorer.scss, app/templates/components/ax-spinner.hbs, app/templates/explorer.hbs, app/templates/welcome.hbs, tests/unit/controllers/explorer-test.js
Needed to be able to search containers yesterday so I went ahead and quickly implemented it.
=> feat- container search implementation

app/controllers/explorer.js, app/styles/app.scss, app/templates/explorer.hbs
Handlebars does not escape style, making it vulnerable to XSS. Bonus
points: Binding classes is more reusable anyway (same goes for the `cursor: pointer`, which I just applied to anything that has an `action` on it).
=> Style Binding Improvements

app/app.js, app/utilities/context-menu.js
=> Add default Window menu for Mac

LICENSE, README.md
=> Introduce GPLv3

app/styles/preview.scss, app/templates/explorer.hbs
=> Restrict Preview Height

app/styles/app.scss, app/styles/breadcrumbs.scss, app/styles/explorer.scss, app/templates/explorer.hbs
=> Breadcrumb Styling

app/styles/explorer.scss
=> Reposition container search field

app/controllers/explorer.js
=> Load first container on load

.jscsrc, app/controllers/application.js, app/styles/explorer.scss, app/styles/preview.scss, package.json
=> Correct Height for Container List

.jscsrc, app/adapters/application.js, app/adapters/container.js, app/controllers/explorer.js, app/controllers/welcome.js, app/routes/explorer.js, app/routes/welcome.js, app/styles/navbar.scss, app/templates/_navbar.hbs
=> Allow switching of active account

.jscsrc, app/adapters/application.js, app/adapters/container.js, app/controllers/explorer.js, app/controllers/welcome.js, app/routes/explorer.js, app/routes/welcome.js, app/styles/navbar.scss, app/templates/_navbar.hbs
Reverts azure-storage/xplat#130
=> Revert "Allow switching of active account"

app/utils/context-menu.js
=> Add DevTools to Context Menu

app/styles/explorer.scss, app/templates/explorer.hbs
=> Fix Breadcrumbs to Top

app/controllers/notifications.js, app/styles/notifications.scss, app/templates/_notification.hbs
=> Notifications: Progress

app/controllers/notifications.js, tests/unit/controllers/explorer-test.js, tests/unit/controllers/notifications-test.js
=> Add Tests for Notifications Controller

.jshintrc, app/adapters/blob.js, app/adapters/container.js, app/components/ax-preview.js, app/controllers/application.js, app/controllers/explorer.js, app/controllers/welcome.js, app/index.html, app/models/setting.js, app/routes/application.js, app/routes/explorer.js, app/routes/welcome.js, app/services/node-services.js, app/templates/application.hbs, app/templates/modals/firstuse.hbs, public/vendor/ai.js, tests/helpers/start-app.js, tests/index.html, tests/unit/controllers/application-test.js, tests/unit/models/setting-test.js, tests/unit/routes/application-test.js
Closes #162 
- Only collected if allowed by the user
=> Anonymized Usage Statistics

app/controllers/explorer.js, app/styles/explorer.scss, app/templates/_navbar.hbs, app/templates/explorer.hbs, app/templates/modals/addcontainer.hbs, tests/unit/controllers/explorer-test.js
=> New UI for "Add Container'

app/controllers/explorer.js, app/templates/explorer.hbs
=> SaveAs Dialog for Single File Download

app/controllers/explorer.js, app/templates/explorer.hbs, app/templates/modals/delete.hbs
=> Download and Delete Folders

app/controllers/explorer.js, app/routes/explorer.js, tests/helpers/start-app.js
=> Improve Explorer

app/styles/explorer.scss, app/templates/explorer.hbs, tests/unit/controllers/notifications-test.js
=> Truncate type, format timestamp

app/controllers/notifications.js, app/models/notification.js, app/styles/notifications.scss, tests/unit/controllers/notifications-test.js
=> Improve Notification Panel

app/controllers/explorer.js, app/templates/explorer.hbs
=> Enable Blob Sorting

Gruntfile.js
=> Copy LICENSE into Dev Builds

app/styles/app.scss, app/styles/explorer.scss, app/styles/welcome.scss, app/templates/welcome.hbs, bower.json
=> Ensure Checkmark Doesn't Blow Up

CONTRIBUTING.md
=> Contributing Guide: Fix List

app/styles/welcome.scss, app/templates/welcome.hbs
Closes #211
- Uses correct FA icons instead of weird telephones.
=> Welcome Screen: Correct Icons

app/templates/_navbar.hbs
Closes #198
- Adds tooltips to the navbar, removing the need for people to guess
what the icons mean
=> Navbar: Add Tooltips

app/styles/explorer.scss
Closes #206
- Simple padding issue.
=> Notifications: Don't Hide Table

app/routes/application.js, app/routes/explorer.js, app/utils/context-menu.js, app/utils/window-menu.js
Ref #196
- Window Menu works on OS X, somehow doesn’t on Windows, so we still
need to work on that.
=> Window Menu

CONTRIBUTING.md, Gruntfile.js, dependencies.txt, package.json
Documenting the few additional steps required to make the development pipeline run on Windows.
=> Readme for Windows Installation

app/controllers/blob.js, app/controllers/explorer.js, app/routes/explorer.js, app/templates/explorer.hbs, app/templates/modals/blob-properties.hbs, app/utils/context-menu.js
- Managed to get rid of a bunch of code, is now more performant
- Simplified template
- Added moment and prettySize to properties
- Modal design consistent with other modals
=> Improve 'Display Properties'

app/components/ax-preview.js, app/routes/explorer.js, tests/integration/explorer-test.js
Closes #242
- Also added a simple integration test
=> Fix 'Go Home' Regression

app/styles/app.scss, app/styles/blob-properties.scss, app/templates/_modal_navbar.hbs, app/templates/modals/about.hbs, app/templates/modals/addcontainer.hbs, app/templates/modals/blob-properties.hbs, app/templates/modals/delete.hbs, app/templates/modals/deletecontainer.hbs, app/templates/modals/error.hbs, app/templates/modals/upload.hbs, app/views/modal-navbar.js, tests/unit/views/modal-navbar-test.js
Creates a nav bar reusable for all modals providing optional tabs when necessary.
=> feat(modals/navbar) - consistent navbar view for every modal

postcompile/windows/Azure Storage Explorer.aip
To be used with Advanced Installer
=> Windows Installer AIP

tests/helpers/combined-start.js, tests/helpers/resolver.js, tests/unit/controllers/application-test.js, tests/unit/controllers/blob-test.js, tests/unit/controllers/explorer-test.js, tests/unit/controllers/notifications-test.js, tests/unit/controllers/uploaddownload-test.js, tests/unit/controllers/welcome-test.js
=> Improve Tests

app/controllers/explorer.js, app/templates/explorer.hbs, tests/integration/notification-test.js
=> Checkbox for 'select all blobs'

app/controllers/explorer.js, app/controllers/uploaddownload.js, app/models/container.js, app/routes/explorer.js, app/templates/_navbar.hbs, app/templates/explorer.hbs, app/templates/modals/copy.hbs, app/utils/string-resources.js, app/utils/window-menu.js, tests/helpers/start-app.js, tests/unit/controllers/explorer-test.js
closes #210, #241
- Prevent users from creating new containers with no name
- Convert container name to all lowercase per Azure container naming conversion
- New feature to copy blob
=> Implement copyblobs, fix creation of containers

app/controllers/uploaddownload.js, app/models/blob.js, package.json
Closes #249
- Currently not implemented: Recursive download. We now download
dir/file.ext into dir/file.ext, but we ignore dir1/dir2/file.ext if
dir1 is selected.
=> Enable directory download

app/controllers/application.js, app/templates/modals/about.hbs
=> Add Rita to Credits

CONTRIBUTING.md
=> Added Dev Tools Info

app/controllers/welcome.js, app/routes/application.js, app/styles/welcome.scss, app/templates/modals/error.hbs, app/templates/welcome.hbs, app/utils/string-resources.js, tests/acceptance/explorer-test.js, tests/acceptance/notification-test.js, tests/acceptance/welcome-test.js, tests/helpers/combined-start.js
Added drop down and the related tests.  Also moved error messages from application.js to string resources.  Tests all pass but I am unable to figure out how to test "dismissing" the error dialog.
=> As per @sedouard Added dns suffix drop down

app/controllers/explorer.js, app/routes/explorer.js
We previously initiated drag & drop on the controller's init, which is only run once when the object is instantiated for the first time.
This commit moves it to the `setupController` phase of the route, ensure that it runs every time. 
Closes #281
=> Setup Drag & Drop on Route

.travis.yml, Gruntfile.js, postcompile/deploy.sh
Also ensured that packaging the app is still tested on PRs.
=> Improve Module Flattening for Dev Builds

Gruntfile.js, package.json
Fixes a small issue that kept us from deploying windows build files
=> Small Build/Deploy Fix

app/controllers/welcome.js, app/routes/welcome.js, config/environment.js
Stupid mistake.  Somehow the drop down shows that the default dns suffix is selected but it is not getting saved.  I added a check to make sure that if none is selected that it defaults to blob.core.windows.net.
=> Fix dns suffix save

app/adapters/blob.js, app/adapters/container.js, app/adapters/service-settings.js, tests/helpers/start-app.js
Force adapters to throw exceptions for better UX
=> fix(adapters) - adapters throw execptions

.vscode/settings.json, app/controllers/explorer.js, app/utils/string-resources.js
This should close #297
Validates container names with a regex.
=> Validate container names

Gruntfile.js, app/controllers/explorer.js
We’ll now replaces any spaces with a `-` dash.
Closes #350
=> Don't allow container names with spaces

app/routes/welcome.js
Should now really close issue #306
=> default to the previously selected account when returning from browsing

package.json
=> Upgrade Azure Storage Node SDK

releasenotes.html
Adding notes for 2 fixes done for the 6/15 release: Table node issue with local storage emulator & eliminate unnecessary setup steps.
=> Website for20160608 release

releasenotes.html
Remove the notes on the setup change which didn't make into this release
=> Remove the notes on the setup change which didn't make into this release

index.html, releasenotes.html
Adding links to download previous releases in index.html.
=> Adding links to download previous releases in index.html.

index.html, releasenotes.html, stylesheets/stylesheet.css
Storage Explorer Sept 2016 release notes
=> Sept 2016 release notes

index.html, releasenotes.html
Adding the release demo video for the Sept 2016 release
=> Sept 2016 Release demo video

index.html, releasenotes.html
Using https instead of http to improve security
=> change http to https

index.html, releasenotes.html
0.8.7 landing page and release notes update
=> 0.8.7 release

index.html, releasenotes.html
=> Correct a spelling "Flashed" to "Flashes"

index.html, releasenotes.html
Updated homepage and release notes page.
=> 0.8.8 release

index.html
Updated "Previous Version" section.
Added national cloud support to the feature list.
=> Updated "Previous Version" section

index.html, releasenotes.html
1. Adding release notes for v0.8.10 release
2. Change copyright to 2017
=> 0.8.10 release notes updates

index.html, releasenotes.html
Up the release to 0.8.11 after fixing the conflict resolution issue.
=> Up the release to 0.8.11 after fixing the conflict resolution issue

index.html, releasenotes.html
Up the release notes to 0.8.12 to include the sending feedback fix.
=> Up the release notes to 0.8.12 to include the sending feedback fix

index.html, releasenotes.html
=> 0.8.13 release notes on 5/12/2017

index.html, releasenotes.html
0.8.14 release note. This is to upgrade Electron to 1.7.2 and Chromium to 58.
=> 0.8.14 releasenotes

index.html
Fixed version number for the previous version section in the release notes
=> Fixed version number for the previous versions section in the release notes

index.html, releasenotes.html
Also includes the SE website homepage changes.
=> 0.8.15 Release Notes
